# Generated by Django 3.0.5 on 2020-04-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20200425_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Մարդատար', 'Մարդատար'), ('2', 'Բեռնատար'), ('3', 'Մոտոտեխնիկա'), ('4', 'Հատուկ տեխնիկա'), ('5', 'Ավտոբուս'), ('6', 'Կցասայլ'), ('7', 'Հեծանիվ'), ('8', 'Ջրային տեխնիկա')], max_length=30, null=True),
        ),
    ]
