# Generated by Django 3.0.5 on 2020-05-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20200501_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(default='Pictures/default.jpg', upload_to='Pictures/'),
        ),
    ]
