# Generated by Django 3.0.5 on 2020-05-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_auto_20200503_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Սպիտակ', 'Սպիտակ'), ('Սև', 'Սև'), ('ԱրծաթագույՆ', 'Արծաթագույն'), ('Կապույտ', 'Կապույտ'), ('Կարմիր', 'Կարմիր')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='color_of_the_hall',
            field=models.CharField(choices=[('Սպիտակ', 'Սպիտակ'), ('Սև', 'Սև'), ('ԱրծաթագույՆ', 'Արծաթագույն'), ('Կապույտ', 'Կապույտ'), ('Կարմիր', 'Կարմիր')], max_length=30, null=True),
        ),
    ]
